{{- if and .Values.metrics.enabled .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-r8r.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-r8r.labels" . | nindent 4 }}
spec:
  ports:
    - name: {{ if .Values.metrics.secure }}https{{ else }}http{{ end }}
      port: {{ .Values.metrics.port }}
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "k8s-r8r.selectorLabels" . | nindent 4 }}
{{- end }}
